### ISSUE TITLE
Некорректное отображение меток по осям

### ISSUE THREAD

**Issue by Toucandy** [aivn/aiwlib#1]
Цифры по вертикальной и горизонтальной осям не помещаются на экран

![Screenshot from 2020-06-10 23-11-40](https://user-images.githubusercontent.com/31469363/84314330-8ab49a00-ab70-11ea-911c-5f7b53f0a400.png)
![Screenshot from 2020-06-10 23-11-20](https://user-images.githubusercontent.com/31469363/84314334-8be5c700-ab70-11ea-885e-9a905685f581.png)

**Comment by Toucandy** [comment]
По всей видимости дело во fractional scaling 150% (gnome 3)

**Comment by aivn** [comment]
Проблема была связана с неправильным расчетом размера текста на канвасе.
В настройки добавлено поле font_scale, его можно задавать в конифг-файле ~/.uplt 

content.settings.font_scale.set(1.5)
